name: medicare
description: "Your Health Partner - An app to connect health experts with patients for seamless healthcare solutions."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.0
  firebase_messaging: ^14.6.7
  google_sign_in: ^5.4.2
  cupertino_icons: ^1.0.8
  async: any
  collection: any
  http: ^1.4.0

dependency_overrides:
  web: 0.5.0
  firebase_core_web: 2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/doctor.png
    - assets/images/verify_email-removebg-preview.png
    - assets/images/profilepicture.png
    - assets/images/medicarehero.jpg
    - assets/images/avatar1.jpg
    - assets/images/doctor.jpg
    - assets/images/team2.png
    - assets/images/pharmacy1.jpg
    - assets/images/pharmacy2.jpg
    - assets/images/hospital1.jpg
    - assets/images/hospital2.jpg
    - assets/images/Rectangle 7 (1).png
    - assets/images/Rectangle 7.png
