// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBme63FhKBwlPE1dLzZCG1rtfcgfS_lumU',
    appId: '1:494322579031:web:ccefaf392073c596fd1512',
    messagingSenderId: '494322579031',
    projectId: 'medicare-94e5c',
    authDomain: 'medicare-94e5c.firebaseapp.com',
    storageBucket: 'medicare-94e5c.firebasestorage.app',
    measurementId: 'G-PR2G1VDP5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVe1ZDUUxtdeMVKjm_ZiWIPZEYFf4HH68',
    appId: '1:494322579031:android:880e358cf850767efd1512',
    messagingSenderId: '494322579031',
    projectId: 'medicare-94e5c',
    storageBucket: 'medicare-94e5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-4bmQL-9zvLG0M7P-v1eazW4o0AE1-o',
    appId: '1:494322579031:ios:b75f0c43102a5286fd1512',
    messagingSenderId: '494322579031',
    projectId: 'medicare-94e5c',
    storageBucket: 'medicare-94e5c.firebasestorage.app',
    androidClientId: '494322579031-ivhmsrccmlav4j7o12vpsvopi8mq5sbo.apps.googleusercontent.com',
    iosClientId: '494322579031-pqf08if8gpg7622b3gjso3bbmoieq5ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-4bmQL-9zvLG0M7P-v1eazW4o0AE1-o',
    appId: '1:494322579031:ios:b75f0c43102a5286fd1512',
    messagingSenderId: '494322579031',
    projectId: 'medicare-94e5c',
    storageBucket: 'medicare-94e5c.firebasestorage.app',
    androidClientId: '494322579031-ivhmsrccmlav4j7o12vpsvopi8mq5sbo.apps.googleusercontent.com',
    iosClientId: '494322579031-pqf08if8gpg7622b3gjso3bbmoieq5ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBme63FhKBwlPE1dLzZCG1rtfcgfS_lumU',
    appId: '1:494322579031:web:8d18228cc458af38fd1512',
    messagingSenderId: '494322579031',
    projectId: 'medicare-94e5c',
    authDomain: 'medicare-94e5c.firebaseapp.com',
    storageBucket: 'medicare-94e5c.firebasestorage.app',
    measurementId: 'G-CZJ483JZ1P',
  );
}
